project:
  type: book
  output-dir: documentation/docs
  

book:
  title: "North-Country-Wild Repo Documentation"
  author: "Erika Barthelmess"
  page-navigation: true
  page-footer: 
    left: "Copyright 2025, Erika L. Barthelmess"
  chapters:
    - index.qmd
    - documentation/intro.qmd
    - documentation/who-we-are.qmd
    - documentation/Chapter-1.qmd
    - documentation/Chapter-2.qmd
    - documentation/references.qmd

bibliography: documentation/references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

